version: '3'
services:
  proxy:
    image: clari23/bananajnkins
    container_name: clacontainer
    build:
      context: .
    #volumes:
    #  - .\site:/usr/share/nginx/htm
    #volumes:
    #  - site:/usr/share/nginx/htm
    #ports: definir a porta de entrada host:container
    ports:
      - "80:8080"
    networks:
      - tartanet

networks:
  tartanet:
    driver: bridge

    #volumes:
    #  site:

    # docker-compose up -d